# -*- coding: utf-8 -*-
"""reconhecimento de face.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4DnMhZvX_onWmgvikztnD3yhlZDHOVp
"""

!pip install face_recognition

!mkdir desconhecidos
!wget https://cdn-images-1.medium.com/max/1200/1*aEoYLgy4z1lT1kW7dqWzBg.jpeg -O desconhecidos/1.jpg
!wget https://media-cldnry.s-nbcnews.com/image/upload/t_fit-760w,f_auto,q_auto:best/newscms/2017_46/2224911/171113-bill-gates-se-247p.jpg -O desconhecidos/2.jpg
!wget https://specials-images.forbesimg.com/imageserve/1184274010/960x0.jpg -O desconhecidos/3.jpg
!wget https://i.insider.com/5ddfa893fd9db26b8a4a2df7 -O desconhecidos/4.jpg
!wget https://static.wikia.nocookie.net/simpsons/images/8/8e/Bill_Gates.png -O desconhecidos/5.jpg
!wget https://image.cnbcfm.com/api/v1/image/104924313-obama-gates.jpg -O desconhecidos/6.jpg

!mkdir conhecidos
!wget https://t.ctcdn.com.br/_Sx_1_ut0ubvJSZ6gy9KFYiNmDE=/400x400/smart/i490763.jpeg -O conhecidos/bill.jpeg
!wget https://upload.wikimedia.org/wikipedia/commons/c/c4/President_Barack_Obama_%28cropped%29.jpg -O conhecidos/obama.jpg

import face_recognition
import cv2
import os
from google.colab.patches import csv_imShow

#Redimencionar as imagens
def read_img(path):
  img = cv2.imread(path)
  (h,w) = img.shape[:2]
  width = 500
  ratio = width / float(w)
  height = int(h * ratio)
  return cv2.resize(img, (width, height))

known_encoding = []
known_names = []
known_dir = 'conhecidos'

for file in os.listdir(unknown_dir):
    print("Processing", file)
    img = read_img(unknown_dir + '/' + file)
    img_enc = face_recognition.face_encodings(img)[0]

    results = face_recognition.compare_faces(known_encoding, img_enc)
    # print(face_recognition.face_distance(known_encodings, img_enc))
    for i in range(len(results)):
        if results[i]:
            name = known_names[i]
            (top, right, bottom, left) = face_recognition.face_locations(img)[0]
            cv2.rectangle(img, (left, top), (right, bottom), (0, 0, 255), 2)
            cv2.putText(img, name, (left+2, bottom+20), cv2.FONT_HERSHEY_PLAIN, 1, (255, 255, 255), 1)
            cv2_imshow(img)